### ISSUE TITLE
manual de deployment

### ISSUE THREAD

**Issue by wgnann** [ime-usp-br/alocacao#4]
parece seguir um modelo tradicional (`composer, copiar env com replicado, key:generate, migrate:fresh --seed`), mas não tem informação sobre as queues (o `.env.example` diz que são `sync`)

**Comment by ayrtonnotrya** [comment]
O deploy foi descrito no readme.md (d1b356138b92fbf1d8ee03e3a3e49de3d3660e51) e o env.example foi corrigido (b01dd8cbe1c91c039d87d9a23f55dc9c58816c47).
