### ISSUE TITLE
acoplamento com o replicado no show.blade.php

### ISSUE THREAD

**Issue by wgnann** [ime-usp-br/alocacao#5]
Não sei se é by design, mas ocorre que `$instructor->getPronounTreatment()` chama o replicado e falha quando o replicado não responder.

Uma possibilidade seria meramente não usar o replicado para esse tipo de funcionalidade. Outra passaria por verificar se ele está acessível antes e falhar graciosamente.

Como não parece se tratar de algo que garanta a consistência e, além disso, já há uma rotina para importação do replicado, talvez seja só o caso de desacoplar.

**Comment by ayrtonnotrya** [comment]
Obrigado pela observação, realmente fazer todas essas consultas no replicado no momento de gerar a view com certeza deixa muito mais lento. Removi os pronomes de tratamento das view no commit 5744cb299e2c78b27ec4784863ea91b9d8e98334
