### ISSUE TITLE
views versus controllers

### ISSUE THREAD

**Issue by wgnann** [ime-usp-br/alocacao#6]
Ainda no `show.blade.php` percebi que existem diversas seções de código que chamam o PHP e instanciam objetos. Pelo paradigma do MVC, isso deveria ser feito no controlador e passado pelo `context`.

Geralmente usar `@php` dentro de um blade deveria ser exceção. Na realidade, eu não consegui pensar num exemplo cuja manipulação de objeto não devesse ser realizada dentro do controller.

**Comment by ayrtonnotrya** [comment]
Foi atendido no commit d785ad4eb50ea0d4621b729963cf8e35d5a9fa2f
